"""
Pre-built hook scripts and configuration generators for Antigravity (agy) CLI.
"""

import json
import os
from typing import Any, Dict, List, Optional, Union
from termreel.hooks.models import HookEventType, HookDecision


def generate_hook_script(
    bridge_file: Optional[str] = None,
    auto_approve: bool = True,
    log_events: bool = True,
    custom_policy: Optional[Dict[str, str]] = None,
) -> str:
    """
    Generate the Python source code for the standalone hook script executed by agy.
    The script parses JSON from stdin, writes telemetry to the bridge file, and outputs
    verdict decisions to stdout.
    """
    bridge_file_repr = repr(bridge_file)
    policy_repr = repr(custom_policy or {})
    auto_approve_repr = repr(auto_approve)
    log_events_repr = repr(log_events)

    return f'''#!/usr/bin/env python3
\"\"\"
TermReel hook handler script for Antigravity (agy) lifecycle events.
Auto-generated by TermReel.
\"\"\"

import json
import os
import sys
import time

BRIDGE_FILE = {bridge_file_repr}
AUTO_APPROVE = {auto_approve_repr}
LOG_EVENTS = {log_events_repr}
CUSTOM_POLICY = {policy_repr}


def main():
    # 1. Parse stdin JSON payload
    try:
        raw_input = sys.stdin.read().strip()
        data = json.loads(raw_input) if raw_input else {{}}
    except Exception:
        data = {{}}

    # 2. Determine Event Type (CLI argument -> stdin field -> env var -> heuristics)
    if len(sys.argv) > 1 and sys.argv[1].strip():
        event_type = sys.argv[1].strip()
    elif data.get("event_type") or data.get("event") or data.get("hook_event"):
        event_type = data.get("event_type") or data.get("event") or data.get("hook_event")
    elif os.environ.get("AGY_HOOK_EVENT"):
        event_type = os.environ["AGY_HOOK_EVENT"]
    elif "toolCall" in data or "tool_call" in data:
        event_type = "PostToolUse" if ("toolOutput" in data or "output" in data or "error" in data) else "PreToolUse"
    elif "invocationNum" in data or "initialNumSteps" in data:
        event_type = "PreInvocation"
    elif "terminationReason" in data or "fullyIdle" in data:
        event_type = "Stop"
    else:
        event_type = "PreToolUse"

    # 3. Extract tool call information (supports Antigravity camelCase protojson)
    tool_call = data.get("toolCall") or data.get("tool_call") or {{}}
    if isinstance(tool_call, dict) and tool_call:
        tool_name = tool_call.get("name") or data.get("tool_name") or data.get("tool")
        tool_args = tool_call.get("args") or data.get("tool_args") or data.get("args")
    else:
        tool_name = data.get("tool_name") or data.get("tool") or data.get("name")
        tool_args = data.get("tool_args") or data.get("args") or data.get("arguments")

    tool_output = data.get("tool_output") or data.get("toolOutput") or data.get("output") or data.get("result")
    session_id = (
        data.get("conversationId")
        or data.get("conversation_id")
        or data.get("session_id")
        or os.environ.get("AGY_SESSION_ID")
    )
    step_idx = data.get("stepIdx") or data.get("step_idx")
    invocation_num = data.get("invocationNum") or data.get("invocation_num")
    term_reason = data.get("terminationReason") or data.get("termination_reason")
    prompt = data.get("prompt") or data.get("user_prompt") or data.get("userPrompt")
    response = data.get("response") or data.get("model_response") or data.get("modelResponse")
    error_msg = data.get("error") or data.get("error_message") or data.get("errorMessage")
    ws_paths = data.get("workspacePaths") or data.get("workspace_paths")
    tr_path = data.get("transcriptPath") or data.get("transcript_path")
    art_path = data.get("artifactDirectoryPath") or data.get("artifact_directory_path")
    model_name = data.get("modelName") or data.get("model_name")

    # 4. Evaluate decision and prepare response
    clean_ev = event_type.replace("_", "").lower()
    decision = "allow"
    reason = None

    if "pretool" in clean_ev:
        if tool_name and tool_name in CUSTOM_POLICY:
            pol = CUSTOM_POLICY[tool_name].lower()
            if pol == "deny":
                decision = "deny"
                reason = f"TermReel policy denied tool '{{tool_name}}'"
            elif pol in ("ask", "force_ask"):
                decision = pol
                reason = f"TermReel policy requested prompt for tool '{{tool_name}}'"
            else:
                decision = "allow"
        elif not AUTO_APPROVE:
            decision = "ask"
        else:
            decision = "allow"

        out = {{"decision": decision, "allow": (decision == "allow")}}
        if reason:
            out["reason"] = reason
            out["message"] = reason
    elif "posttool" in clean_ev:
        out = {{}}
    elif "preinvoc" in clean_ev:
        out = {{"injectSteps": []}}
    elif "postinvoc" in clean_ev:
        out = {{"injectSteps": [], "terminationBehavior": ""}}
    elif "stop" in clean_ev:
        out = {{}}
    else:
        out = {{"decision": decision, "allow": (decision == "allow")}}
        if reason:
            out["reason"] = reason
            out["message"] = reason

    # 5. Telemetry logging to JSONL bridge file
    if LOG_EVENTS and BRIDGE_FILE:
        event_record = {{
            "event_type": event_type,
            "timestamp": time.time(),
            "tool_name": tool_name,
            "tool_args": tool_args,
            "tool_output": tool_output,
            "session_id": session_id,
            "prompt": prompt,
            "response": response,
            "decision": decision,
            "reason": reason,
            "error_message": error_msg,
            "step_idx": step_idx,
            "invocation_num": invocation_num,
            "termination_reason": term_reason,
            "workspace_paths": ws_paths,
            "transcript_path": tr_path,
            "artifact_directory_path": art_path,
            "model_name": model_name,
        }}
        try:
            with open(BRIDGE_FILE, "a", encoding="utf-8") as f:
                f.write(json.dumps(event_record) + "\\n")
                f.flush()
        except Exception:
            pass

    # 6. Emit stdout contract to Antigravity CLI and exit cleanly (0)
    sys.stdout.write(json.dumps(out) + "\\n")
    sys.stdout.flush()
    sys.exit(0)


if __name__ == "__main__":
    main()
'''


def create_agy_hooks_config(
    hook_script_path: str,
    events: Optional[List[str]] = None,
    matcher: str = "*",
    hook_name: str = "termreel",
) -> Dict[str, Any]:
    """
    Build standard .agents/hooks.json dictionary mapping for Antigravity (agy).
    Supports all core lifecycle events: PreToolUse, PostToolUse, PreInvocation,
    PostInvocation, Stop.
    """
    target_events = events or [
        HookEventType.PRE_TOOL_USE.value,
        HookEventType.POST_TOOL_USE.value,
        HookEventType.PRE_INVOCATION.value,
        HookEventType.POST_INVOCATION.value,
        HookEventType.STOP.value,
    ]

    group_config: Dict[str, Any] = {"enabled": True}

    for ev in target_events:
        norm = HookEventType.from_string(ev).value
        cmd = f"python3 {hook_script_path} {norm}"
        if norm in (HookEventType.PRE_TOOL_USE.value, HookEventType.POST_TOOL_USE.value):
            group_config[norm] = [
                {
                    "matcher": matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": cmd,
                            "timeout": 15.0,
                        }
                    ],
                }
            ]
        else:
            group_config[norm] = [
                {
                    "type": "command",
                    "command": cmd,
                    "timeout": 15.0,
                }
            ]

    return {
        hook_name: group_config,
    }


def create_auto_approve_policy(
    allowed_tools: Optional[List[str]] = None,
    denied_tools: Optional[List[str]] = None,
) -> Dict[str, str]:
    """Helper creating a custom tool policy dictionary."""
    policy: Dict[str, str] = {}
    if allowed_tools:
        for t in allowed_tools:
            policy[t] = "allow"
    if denied_tools:
        for t in denied_tools:
            policy[t] = "deny"
    return policy


DEFAULT_ALLOWED_COMMANDS: List[str] = [
    "python3",
    "python3 app.py",
    "python",
    "pytest",
    "pytest -v",
    "git",
    "git status",
    "git diff",
    "git log",
    "git add",
    "git commit",
    "cat",
    "ls",
    "echo",
    "touch",
    "mkdir",
    "npm",
    "npm test",
    "npm run lint",
    "node",
    "yarn",
    "cargo",
    "make",
    "bash",
]


KNOWN_AGENT_TOOLS: set = {
    "run_command",
    "write_to_file",
    "replace_file_content",
    "edit_file",
    "read_file",
    "write_file",
    "list_dir",
    "view_file",
    "find_by_name",
    "grep_search",
    "code_search",
    "moma_search",
    "search_web",
    "web_search",
    "ask_question",
    "ask_permission",
    "ask_custom_permission",
    "generate_image",
    "read_url_content",
    "read_browser_page",
    "call_mcp_tool",
    "list_resources",
    "read_resource",
    "manage_task",
    "schedule",
    "send_message",
    "skill_search",
    "notebook_edit",
    "terminal",
}


def normalize_permission_string(perm: str) -> str:
    """Normalize a permission rule string into agy settings format (e.g. 'command(python3)')."""
    perm = str(perm).strip()
    if not perm:
        return ""
    if perm.startswith("tool:") or perm.startswith("tool_name:"):
        t_val = perm.split(":", 1)[1].strip()
        return t_val
    if perm.startswith("tool(") and perm.endswith(")"):
        return perm[5:-1].strip()
    if perm in KNOWN_AGENT_TOOLS:
        return perm
    if "(" in perm and perm.endswith(")"):
        return perm
    if perm.startswith("command:") or perm.startswith("cmd:"):
        cmd_val = perm.split(":", 1)[1].strip()
        return f"command({cmd_val})"
    if perm.startswith("read_file:") or perm.startswith("read:") or perm.startswith("read_path:"):
        p_val = perm.split(":", 1)[1].strip()
        return f"read_file({p_val})"
    if perm.startswith("write_file:") or perm.startswith("write:") or perm.startswith("write_path:"):
        p_val = perm.split(":", 1)[1].strip()
        return f"write_file({p_val})"
    if perm.startswith("read_url:") or perm.startswith("url:"):
        u_val = perm.split(":", 1)[1].strip()
        return f"read_url({u_val})"
    if perm.startswith("execute_url:"):
        u_val = perm.split(":", 1)[1].strip()
        return f"execute_url({u_val})"
    if perm.startswith("mcp:"):
        m_val = perm.split(":", 1)[1].strip()
        return f"mcp({m_val})"
    if perm.startswith("custom:"):
        c_val = perm.split(":", 1)[1].strip()
        return f"custom({c_val})"
    if perm.startswith("unsandboxed:"):
        u_val = perm.split(":", 1)[1].strip()
        return f"unsandboxed({u_val})"
    if perm.startswith("escalate_admin:"):
        e_val = perm.split(":", 1)[1].strip()
        return f"escalate_admin({e_val})"
    return f"command({perm})"


def create_agy_settings_config(
    permissions: Optional[Union[List[str], Dict[str, Any]]] = None,
    custom_settings: Optional[Dict[str, Any]] = None,
    enable_terminal_sandbox: bool = False,
    auto_allow_common: bool = True,
    model: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate standard .agents/settings.json dictionary for Antigravity (agy) CLI.
    Pre-configures permission allowlists, terminal sandbox policies, and custom overrides.
    """
    allow_rules: List[str] = []
    deny_rules: List[str] = []
    mode = "request-review"
    sandbox = enable_terminal_sandbox

    if auto_allow_common:
        for cmd in DEFAULT_ALLOWED_COMMANDS:
            rule = normalize_permission_string(cmd)
            if rule and rule not in allow_rules:
                allow_rules.append(rule)

    if isinstance(permissions, list):
        for p in permissions:
            if isinstance(p, str):
                rule = normalize_permission_string(p)
                if rule and rule not in allow_rules:
                    allow_rules.append(rule)
    elif isinstance(permissions, dict):
        if "mode" in permissions:
            mode = str(permissions["mode"])
        if "enable_terminal_sandbox" in permissions:
            sandbox = bool(permissions["enable_terminal_sandbox"])
        if "enableTerminalSandbox" in permissions:
            sandbox = bool(permissions["enableTerminalSandbox"])

        for p in permissions.get("allow", []):
            if isinstance(p, str):
                rule = normalize_permission_string(p)
                if rule and rule not in allow_rules:
                    allow_rules.append(rule)

        for cmd in permissions.get("allowed_commands", permissions.get("commands", [])):
            if isinstance(cmd, str):
                rule = f"command({cmd.strip()})"
                if rule not in allow_rules:
                    allow_rules.append(rule)

        for t in permissions.get("allowed_tools", permissions.get("tools", [])):
            if isinstance(t, str):
                rule = normalize_permission_string(t.strip())
                if rule not in allow_rules:
                    allow_rules.append(rule)

        for pth in permissions.get("allowed_paths", permissions.get("read_paths", permissions.get("read_files", []))):
            if isinstance(pth, str):
                rule = f"read_file({pth.strip()})"
                if rule not in allow_rules:
                    allow_rules.append(rule)

        for pth in permissions.get("write_paths", permissions.get("write_files", [])):
            if isinstance(pth, str):
                rule = f"write_file({pth.strip()})"
                if rule not in allow_rules:
                    allow_rules.append(rule)

        for url in permissions.get("allowed_urls", permissions.get("urls", [])):
            if isinstance(url, str):
                rule = f"read_url({url.strip()})"
                if rule not in allow_rules:
                    allow_rules.append(rule)

        for d in permissions.get("deny", []):
            if isinstance(d, str):
                rule = normalize_permission_string(d)
                if rule and rule not in deny_rules:
                    deny_rules.append(rule)

    settings_dict: Dict[str, Any] = {
        "enableTerminalSandbox": sandbox,
        "permissions": {
            "mode": mode,
            "allow": allow_rules,
        },
    }

    if deny_rules:
        settings_dict["permissions"]["deny"] = deny_rules

    if model:
        settings_dict["model"] = model

    # Merge custom settings overrides
    if custom_settings and isinstance(custom_settings, dict):
        for k, v in custom_settings.items():
            if k == "permissions" and isinstance(v, dict):
                if "mode" in v:
                    settings_dict["permissions"]["mode"] = v["mode"]
                if "allow" in v and isinstance(v["allow"], list):
                    for item in v["allow"]:
                        rule = normalize_permission_string(str(item))
                        if rule not in settings_dict["permissions"]["allow"]:
                            settings_dict["permissions"]["allow"].append(rule)
                if "deny" in v and isinstance(v["deny"], list):
                    if "deny" not in settings_dict["permissions"]:
                        settings_dict["permissions"]["deny"] = []
                    for item in v["deny"]:
                        rule = normalize_permission_string(str(item))
                        if rule not in settings_dict["permissions"]["deny"]:
                            settings_dict["permissions"]["deny"].append(rule)
            else:
                settings_dict[k] = v

    return settings_dict

