"""
Pre-built hook scripts and configuration generators for Antigravity (agy) CLI.
"""

import json
import os
from typing import Any, Dict, List, Optional
from termreel.hooks.models import HookEventType, HookDecision


def generate_hook_script(
    bridge_file: Optional[str] = None,
    auto_approve: bool = True,
    log_events: bool = True,
    custom_policy: Optional[Dict[str, str]] = None,
) -> str:
    """
    Generate the Python source code for the standalone hook script executed by agy.
    The script parses JSON from stdin, writes telemetry to the bridge file, and outputs
    verdict decisions to stdout.
    """
    bridge_file_repr = repr(bridge_file)
    policy_repr = repr(custom_policy or {})
    auto_approve_repr = repr(auto_approve)
    log_events_repr = repr(log_events)

    return f'''#!/usr/bin/env python3
"""
TermReel hook handler script for Antigravity (agy) lifecycle events.
Auto-generated by TermReel.
"""

import json
import os
import sys
import time

BRIDGE_FILE = {bridge_file_repr}
AUTO_APPROVE = {auto_approve_repr}
LOG_EVENTS = {log_events_repr}
CUSTOM_POLICY = {policy_repr}


def main():
    try:
        raw_input = sys.stdin.read().strip()
        data = json.loads(raw_input) if raw_input else {{}}
    except Exception:
        data = {{}}

    event_type = data.get("event_type") or data.get("event") or os.environ.get("AGY_HOOK_EVENT", "Unknown")
    tool_name = data.get("tool_name") or data.get("tool") or data.get("name")
    tool_args = data.get("tool_args") or data.get("args") or data.get("arguments")
    tool_output = data.get("tool_output") or data.get("output") or data.get("result")
    session_id = data.get("session_id") or os.environ.get("AGY_SESSION_ID")
    prompt = data.get("prompt") or data.get("user_prompt")
    response = data.get("response") or data.get("model_response")
    error_msg = data.get("error_message") or data.get("error")

    # Determine tool decision
    decision = "allow"
    allow = True
    msg = None

    if event_type in ("PreToolUse", "pre_tool_use", "PreToolCallDecideHook"):
        if tool_name and tool_name in CUSTOM_POLICY:
            pol = CUSTOM_POLICY[tool_name].lower()
            if pol == "deny":
                allow = False
                decision = "deny"
                msg = f"TermReel policy denied tool '{{tool_name}}'"
            else:
                allow = True
                decision = "allow"
        elif AUTO_APPROVE:
            allow = True
            decision = "allow"

    # Telemetry logging to bridge file
    if LOG_EVENTS and BRIDGE_FILE:
        event_record = {{
            "event_type": event_type,
            "timestamp": time.time(),
            "tool_name": tool_name,
            "tool_args": tool_args,
            "tool_output": tool_output,
            "session_id": session_id,
            "prompt": prompt,
            "response": response,
            "decision": decision,
            "error_message": error_msg,
        }}
        try:
            with open(BRIDGE_FILE, "a", encoding="utf-8") as f:
                f.write(json.dumps(event_record) + "\\n")
                f.flush()
        except Exception:
            pass

    # Emit JSON verdict for agy hooks
    out = {{"allow": allow, "decision": decision}}
    if msg:
        out["message"] = msg

    sys.stdout.write(json.dumps(out) + "\\n")
    sys.stdout.flush()
    sys.exit(0 if allow else 1)


if __name__ == "__main__":
    main()
'''


def create_agy_hooks_config(
    hook_script_path: str,
    events: Optional[List[str]] = None,
    matcher: str = "*",
) -> Dict[str, Any]:
    """
    Build standard .agents/hooks.json dictionary mapping for Antigravity (agy).
    Supports all core lifecycle events: PreToolUse, PostToolUse, PreInvocation,
    PostInvocation, SessionStart, SessionEnd.
    """
    target_events = events or [
        HookEventType.PRE_TOOL_USE.value,
        HookEventType.POST_TOOL_USE.value,
        HookEventType.PRE_INVOCATION.value,
        HookEventType.POST_INVOCATION.value,
        HookEventType.SESSION_START.value,
        HookEventType.SESSION_END.value,
    ]

    cmd = f"python3 {hook_script_path}"
    group_config: Dict[str, Any] = {}

    for ev in target_events:
        norm = HookEventType.from_string(ev).value
        if norm in (HookEventType.PRE_TOOL_USE.value, HookEventType.POST_TOOL_USE.value):
            group_config[norm] = [
                {
                    "matcher": matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": cmd,
                            "timeout": 15.0,
                        }
                    ],
                }
            ]
        else:
            group_config[norm] = [
                {
                    "type": "command",
                    "command": cmd,
                    "timeout": 15.0,
                }
            ]

    return {
        "termreel": group_config,
        **group_config,  # Also expose at top-level for maximum backward/forward compatibility
    }


def create_auto_approve_policy(
    allowed_tools: Optional[List[str]] = None,
    denied_tools: Optional[List[str]] = None,
) -> Dict[str, str]:
    """Helper creating a custom tool policy dictionary."""
    policy: Dict[str, str] = {}
    if allowed_tools:
        for t in allowed_tools:
            policy[t] = "allow"
    if denied_tools:
        for t in denied_tools:
            policy[t] = "deny"
    return policy
